# Generated by Django 5.2.5 on 2025-08-26 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
